# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buku', '0001_initial'),
        ('anggota', '0002_auto_20161004_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_akun', models.CharField(choices=[('petugas', 'Petugas'), ('admin', 'Admin')], max_length=9)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('no_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.Buku')),
                ('nrp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.Anggota')),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jabatan', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=10)),
                ('foto', models.ImageField(blank=True, upload_to='D:\\TA\\perpustakaanta\\media_cdn\\upload')),
            ],
        ),
        migrations.AddField(
            model_name='akun',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Petugas'),
        ),
    ]
