# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='jenis_kelamin',
            field=models.CharField(choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
