# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku1',
            name='jenis_buku',
            field=models.CharField(choices=[('kp', 'Kerja Praktek'), ('ta', 'Tugas Akhir'), ('bi', 'Buku Ilmiah')], max_length=5, null=True),
        ),
    ]
