# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_buku', models.CharField(max_length=10)),
                ('judul_buku', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('jenis_buku', models.CharField(choices=[('kp', 'Kerja Praktek'), ('ta', 'Tugas Akhir'), ('bi', 'Buku Ilmiah')], max_length=5)),
            ],
        ),
    ]
